### ISSUE TITLE
Satzung - Repo überarbeiten

### ISSUE THREAD

**Issue by nuest** [DE-RSE/satzung#13]
@BFrit @sdruskat @knarrff 

Mein Vorschlag was hier zu tun wäre:

- [x] PDF der Satzung in oberste Ebene
- [ ] PDF vom Scan des Originals mit Unterschriften muss irgendwo sicher gelagert sein
- [x] Alle vorhandenen Dateien in neuen Ordner "Entwurf"
- [x] Repository https://github.com/DE-RSE/gruendung/ schließen damit nur ein Ort da ist wo die Satzung ist > https://github.com/DE-RSE/gruendung/issues/3
- [x] Deutlichen Hinweis in das Google Doc rein machen, oder es nicht mehr öffentlich teilen (bevorzuge letzteres)
- [x] Satzung auf Seite "Verein" der Webseite verlinken

**Comment by sdruskat** [comment]
Gute Vorschläge. Bin für die Umsetzung.

**Comment by nuest** [comment]
https://github.com/DE-RSE/www/pull/116
