### ISSUE TITLE
Frist für Mitgliedsbeitragzahlung vor JHV

### ISSUE THREAD

**Issue by nuest** [DE-RSE/satzung#16]
Frist muss in Einladung zur JHV erwähnt werden, sollten wir über Geschäftsordnung regeln.

**Comment by knarrff** [comment]
Ich habe in die Einladung 2022 mal folgenden Satz mit aufgenommen:

Noch ein kleiner Hinweis: wahlberechtigt sind nur Vereinsmitglieder, die nicht in Verzug mit den Bei
tragszahlungen sind. Um Probleme am Wahltag zu vermeiden, müssen Beitragszahlungen spätestens drei W
erktage vor der Mitgliederversammlung eingegangen sein.

**Comment by nuest** [comment]
@knarrff Wollen wir vielleicht in unsere Geschäftsordnung den "Entwurf" zur Einladung oder eine Liste mit Dingen die in der Einladung stehen sollen aufnehmen?

**Comment by knarrff** [comment]
So viele Details würde ich nicht in die Geschäftsordnung aufnehmen.
