### ISSUE TITLE
Quelldokument umarbeiten in Text-basiertes Format und Workflow für PDF-Erstellung dokumentieren

### ISSUE THREAD

**Issue by nuest** [DE-RSE/satzung#21]
Derzeit ist das Quelldokument eine Word-Datei - ist nicht so schön zum gemeinsamen Bearbeiten: https://github.com/DE-RSE/satzung/blob/master/de-RSE%20-%20Satzung-V2019-01-07-final.docx

**Comment by knarrff** [comment]
https://github.com/DE-RSE/satzung/blob/master/de-RSE-e.V._Satzung.md
https://github.com/DE-RSE/satzung/blob/master/de-RSE-e.V._Gesch%C3%A4ftsordnung.md
https://github.com/DE-RSE/satzung/blob/master/Makefile
