### ISSUE TITLE
Vereinsvermögen bei Auflösung

### ISSUE THREAD

**Issue by nuest** [DE-RSE/satzung#3]
IMHO ist es für beitretende Mitglieder schöner, schon jetzt zu sehen wem das Vereinsvermögen bei Auflösung zukommt. Der Abschnitt "Vereinsauflösung und gemeinnützige Vermögensbildung" in der Satzung müsste dementsprechend aktualisiert werden.

Vorschläge (auf Basis der Liste `softare_vereine.csv`):

- Deutsche Initiative für Netzwerkinformation e. V.
- Free Software Foundation Europe e.V.,Hamburg
- ~~Free Software Foundation Europe - Chapter Germany e.V.~~ (potentiell D-A-CH)

**Comment by knarrff** [comment]
Das stimmt. Ich bin hier dafuer, jemanden vor allem danach zu waehlen, wie wahrscheinlich es ist, dass es den dortigen Verein dann auch noch gibt, da ich mal davon ausgehe, dass wir nicht wirklich eine baldige Aufloesung unseres Vereins anstreben. Unseren Zielen sollte der Verein schon nahe stehen, aber hauptausschlaggebend sollte "gefuehlte Bestaendigkeit" haben.

Auch nicht vergessen: eine Formulierung was passiert, wenn es "das Ziel" denn dann doch nicht mehr gibt oder es nicht mehr gemeinnuetzig ist (wohl analog zu dem, was im Moment drin ist).

**Comment by nuest** [comment]
Gelöst im aktuellen/finalen Satzungsentwurf:

> ii. Bei Auflösung des Vereins oder bei Wegfall steuerbegünstigter Zwecke fällt sein Vermögen an die "Free Software Foundation Europe e.V.", die es unmittelbar und ausschließlich für steuerbegünstigte Zwecke zu verwenden hat.
> iii. Der Grundsatz der Vermögensbindung ist bei der Fassung von Beschlüssen über die künftige Verwendung des Vereinsvermögens zwingend zu erfüllen.
