### ISSUE TITLE
 Prozedere Entlastung des Vorstands optimieren #71 

### ISSUE THREAD

**Issue by nuest** [DE-RSE/satzung#30]
Manuell transferiert von https://github.com/DE-RSE/vorstand/issues/71 ursprünglich eröffnet von @sdruskat 

---------

"Übliches" Prozedere lt. Mitgliedschaft:

1. Kassenprüfer schlagen Entlastung vor und stellen Antrag auf Entlastung "des Schatzmeisters und des restlichen Vorstandes" (lt. Satzung)
    - [x] Satzung checken und ggf. ändern
3. Abstimmung

**Comment by knarrff** [comment]
Was wollten wir hier nochmal ändern?

**Comment by nuest** [comment]
Steht in der Satzung so drin, der Versammlsungsleiter muss hier nur die Prüfer reden lassen.
