### ISSUE TITLE
Mitgliederausschluss in der Satzung regeln

### ISSUE THREAD

**Issue by nuest** [DE-RSE/satzung#47]
- Ausschluss wollen wir immer über MV machen
- Säumigkeit bei den Mitgliedsbeiträgen explizit als Ausschlussgrund nennen.
- Anhörung durch Vorstand regeln

Gute Infos: https://www.vereinswelt.de/checkliste-vereinsausschluss

Z.B.

![image](https://user-images.githubusercontent.com/1325054/212039101-1550d012-58cd-46f9-8e0d-a5e02ebf4481.png)

**Comment by knarrff** [comment]
Ich bin da eher der Meinung, dass das beim Vorstand bleiben sollte.
