### ISSUE TITLE
Vereinszweck

### ISSUE THREAD

**Issue by BFrit** [DE-RSE/satzung#6]
Geeignete Formulierung eines Vereinszwecks in der Satzung:
Mein Vorschlag:
Zweck des Vereins ist die
- Förderung von Wissenschaft und Forschung durch die Entwicklung von Forschungssoftware und
- die Vernetzung und Weiterbildung der Entwickler von Forschungssoftware

**Comment by StephanJanosch** [comment]
Inspiration: http://www.germanbioimaging.org/wiki/images/7/79/Satzung_GerBI-GMB.pdf


## Paragraph Vereinszweck

de-RSE fördert:

* die Interaktion und den Informationsaustausch innerhalb der wissenschaftlichen Gemeinschaft, zwischen WissenschaftlerInnen und IngenieurInnen und zwischen Hochschulen, Forschungsinstituten und der Industrie;
* die Ausbildung und Fortbildung im Bereich des gesamten Lebenszyklus von Forschungssoftware;
* Sichtbarkeit und Anerkennung / Verbesserte Wahrnehmung der Rolle von Software in der Forschung als Fundament von Veröffentlichungen und Forschungsdaten sowie als deren Bindeglied
* die Zusammenarbeit mit Organisationen, die in verwandten Forschungs- und Technologiegebieten in Deutschland und in Europa aber auch weltweit tätig sind;
* den Informationsaustausch zwischen Wissenschaft und Öffentlichkeit;

Die [Vereinskürzel] verfolgt ausschließlich und unmittelbar gemeinnützige Zwecke
im Sinne des Abschnittes "Steuerbegünstigte Zwecke" der Abgabenordnung. Jede Satzungsänderung soll vor Beschlussfassung mit dem für [Vereinskürzel] zuständigen Finanzamt bezüglich der Vereinbarkeit der Änderung mit dem steuerlichen Gemeinnützigkeitsrecht abgestimmt werden.

## Paragraph Verwirklichung der Satzungszwecke

1. Der Satzungszweck wird im Wesentlichen durch die in den nachfolgenden Absätzen beschriebenen Tätigkeiten und Aktivitäten von [Vereinskürzel] verwirklicht. Als Satzungszwecke werden diese Tätigkeiten nur so lange verfolgt, als sie steuerlich dem ideellen Bereich oder Zweckbetrieben zuzurechnen sind.

2. 

Die Förderung von Wissenschaft im Bereich/Umfeld der Forschungssoftware erfolgt insbesondere durch
a) den Austausch zwischen ordentlichen Mitgliedern, Ehrenmitgliedern und Fördermitgliedern,
b) das Ausrichten wissenschaftlicher Veranstaltungen, Tagungen, Konferenzen u.ä. ,
c) das Ausrichten von Trainingskursen (hard skills und soft skills) für Personen die in der Wissenschaft mit Forschungssoftware interagieren
d) Öffentlichkeitsarbeit und Fortbildung der Allgemeinheit im Bereich der Forschungssoftware.
e) die Beratung von Gesetzgebungs- und Verwaltungsorganen sowie anderer öffentlicher bzw. dem Gemeinwohl verpflichteter Institutionen gemäß den vorgenannten Aufgaben und Zielen
f) Etablierung der Rolle RSE und Stärkung der Tätigkeitsbezeichnung 
g) Förderung von Forschungsvorhaben zum Thema Software in der Wissenschaft
(3) Die Förderung der Nutzung nationaler und internationaler Infrastrukturen im Bereich der wissenschaftlichen Software-Erstellung und Wartung durch fachliche und finanzielle Unterstützung der interessierten WissenschaftlerInnen.
(4) [Vereinskürzel] pflegt den Kontakt mit nationalen und internationalen Organisationen und Einrichtungen, die gleiche oder ähnliche Ziele verfolgen, und unterstützt die Zusammenarbeit.


-------

Was fehlt: de-SSI 

* Sicherstellung von _Sichtbarkeit_, Verifizierbarkeit und Nachhaltigkeit der wissenschaftlichen Softwareentwicklung als Teil von Forschungsprozessen

**Comment by sdruskat** [comment]
Aus PR #7 :
1. Der Satzungszweck wird verwirklicht insbesondere durch
- Durchführung wissenschaftlicher Veranstaltungen zum Themenkomplex Software in der Wissenschaft
- Erstellung und Publikation (auch elektronisch) von Informations- und Schulungsmaterial zum Themenkomplex Software in der Wissenschaft
- Förderung von Forschungsvorhaben, Programmen und Aktivitäten zum Thema Software in der Wissenschaft

**Comment by sdruskat** [comment]
Problemfelder (Website)

### Fehlende Anerkennung für Software-Entwicklung als wissenschaftliche Leistung
- Ziele:
	- Verbesserte Wahrnehmung der Rolle von Software in der Forschung als Fundament von Veröffentlichungen und Forschungsdaten sowie als deren Bindeglied (Website)
	- Verankerung von Software-Veröffentlichungen im wissenschaftlichen Wertesystem durch konsequente Anwendung von DOIs, Referenzierung, Metriken und Reviews (Website) 
	- Sichtbarkeit und Anerkennung / Verbesserte Wahrnehmung der Rolle von Software in der Forschung als Fundament von Veröffentlichungen und Forschungsdaten sowie als deren Bindeglied (ISSUE STEPHAN J.)
- Verwirklichungen:
	- Etablierung der Rolle RSE und Stärkung der Tätigkeitsbezeichnung (Issue #6, Stephan J.)

### Fehlende Verankerung im wissenschaftlichen Reputationssystem
- Ziele:
	- `null`
- Verwirklichungen:
	- Etablierung der Rolle RSE und Stärkung der Tätigkeitsbezeichnung (Issue #6, Stephan J.)

### Eingeschränkte Verfügbarkeit und Nutzbarkeit wissenschaftlicher Software
- Ziele: 
	- Sicherstellung von Nachhaltigkeit und Verifizierbarkeit der wissenschaftlichen Softwareentwicklung als Teil von Forschungsprozessen (Website)
	- Öffnung von wissenschaftlicher Software als zentraler Baustein in Open Science (Website)
- Verwirklichungen:
	- `null`

### Mehrfach- und Parallelentwicklung
- Ziele:
	- `null`
- Verwirklichungen:
	- `null`

### Ungenügende Kompetenzen im Software-Engineering
- Ziele:
	- Professionalisierung von Softwareentwicklung in der Forschung
	- Etablierung der wissenschaftlichen Softwareentwicklung als wesentlicher Bestandteil von Kernkompetenzen insbesondere bei jungen Wissenschaftlern, der kommenden Generation von Forschern (Website)
	- Förderung der Ausbildung und Fortbildung im Bereich des gesamten Lebenszyklus von Forschungssoftware; (Issue #6, Stephan J.)
	- Weiterbildung der Entwickler von Forschungssoftware (Issue #6, Bernadette)
- Verwirklichungen:
	- Schulungen und Anwendung minimal notwendiger Best Practices aus dem Software Engineering (Website)
	- Durchführung von Software Carpentry (SWC) Workshops oder Workshops, die dem SWC Konzept folgen (Website)
	- das Ausrichten von Trainingskursen (hard skills und soft skills) für Personen die in der Wissenschaft mit Forschungssoftware interagieren (Issue #6, Stephan J.)

### Fehlende Qualitätsstandards für die Entwicklung und den Review wissenschaftlicher Software
- Ziele:
	- `null`
- Verwirklichungen:
	- Schulungen und Anwendung minimal notwendiger Best Practices aus dem Software Engineering (Website)
	- Durchführung von Software Carpentry (SWC) Workshops oder Workshops, die dem SWC Konzept folgen (Website)
	- Weiterbildung der Entwickler von Forschungssoftware (Issue #6, Bernadette)
	- das Ausrichten von Trainingskursen (hard skills und soft skills) für Personen die in der Wissenschaft mit Forschungssoftware interagieren (Issue #6, Stephan J.)

### Fehlende Reproduzierbarkeit, z.B. von Simulationsergebnissen
- Ziele:
	- `null`
- Verwirklichungen:
	- `null`

### Unklare Regelungen zur Veröffentlichung in Bezug auf Lizenzen und Intellectual Property (IP)
- Ziele:
	- `null`
- Verwirklichungen:
	- `null`

### `null` 1
- Ziele:
	- Integration in übergeordnete Aktivitäten zum Beispiel im Kontext von e-Science und e-Infrastrukturen (Website)
	- Förderung der Zusammenarbeit mit Organisationen, die in verwandten Forschungs- und Technologiegebieten in Deutschland und in Europa aber auch weltweit tätig sind; (Issue #6, Stephan J.)
- Verwirklichungen:
	- Aufbau eines nationalen, die deutsche Forschungslandschaft übergreifenden Zentrums zum Thema wissenschaftliche Software eingebettet in die e-Science und e-Infrastruktur Bewegung (Website)

### `null` 2
- Ziele:
	- Vereinfachung bei Stellenausschreibungen und der Stellensuche durch Schaffung eines Oberbegriffs sowie Steigerung der Attraktivität des Berufsfeldes (Website)
- Verwirklichungen:
	- Etablierung der Rolle RSE und Stärkung der Tätigkeitsbezeichnung (Issue #6, Stephan J.)

### `null` 3
- Ziele:
	- eine Stimme geben und vertreten gemeinsam unsere Interessen zur Verwirklichung unserer Ziele in der deutschen Wissenschaftslandschaft (Website)
- Verwirklichungen:
	- Bereitstellung eines Forums für den Austausch von den in der bzw. für die Forschung entwickelnden Informatikern, Softwareentwicklern, RSEs und Wissenschaftlern (Website)
	- Etablierung eines Fellowship Programmes, bei dem “Botschafter” (Ambassadors) die Ziele der deutschen RSE Gemeinschaft lokal, regional, national und international vertreten und realisieren (Website)
	- Organisation und Durchführung einer jährlich stattfindenden Konferenz rund um das Thema wissenschaftliche Software nicht nur zum Thema Softwareentwicklung und nicht nur für RSEs (Website)
	- den Austausch zwischen ordentlichen Mitgliedern, Ehrenmitgliedern und Fördermitgliedern, (Issue #6, Stephan J.)
	- das Ausrichten wissenschaftlicher Veranstaltungen, Tagungen, Konferenzen u.ä. (Issue #6, Stephan J.)

### `null` 4
- Ziele:
	- Aufbau von RSE Teams in Forschungsinstituten, Universitäten und anderen wissenschaftlichen Einrichtungen und Organisationen
- Verwirklichungen:
	- `null`

### `null` 5
- Ziele:
	- Aufbau eines nationalen, die deutsche Forschungslandschaft übergreifenden Zentrums zum Thema wissenschaftliche Software eingebettet in die e-Science und e-Infrastruktur Bewegung (Website)
- Verwirklichungen:
	- de-SSI (Issue #6, Stephan J.)

### `null` 6
- Ziele:
	- Vernetzung der Entwickler von Forschungssoftware (Issue #6, Bernadette)
	- die Zusammenarbeit mit Organisationen, die in verwandten Forschungs- und Technologiegebieten in Deutschland und in Europa aber auch weltweit tätig sind; (Issue #6, Stephan J.)
- Verwirklichungen:
	- den Austausch zwischen ordentlichen Mitgliedern, Ehrenmitgliedern und Fördermitgliedern, (Issue #6, Stephan J.)
	- das Ausrichten wissenschaftlicher Veranstaltungen, Tagungen, Konferenzen u.ä. (Issue #6, Stephan J.)

### `null` 7
- Ziele:
	- Förderung der Interaktion und den Informationsaustausch innerhalb der wissenschaftlichen Gemeinschaft, zwischen WissenschaftlerInnen und IngenieurInnen und zwischen Hochschulen, Forschungsinstituten und der Industrie; (Issue #6, Stephan J.)
	- Förderung der Zusammenarbeit mit Organisationen, die in verwandten Forschungs- und Technologiegebieten in Deutschland und in Europa aber auch weltweit tätig sind; (Issue #6, Stephan J.)
	- [Vereinskürzel] pflegt den Kontakt mit nationalen und internationalen Organisationen und Einrichtungen, die gleiche oder ähnliche Ziele verfolgen, und unterstützt die Zusammenarbeit. (Issue #6, Stephan J.)
- Verwirklichungen:
	- `null`

### `null` 8
- Ziele:
	- Förderung des Informationsaustausch zwischen Wissenschaft und Öffentlichkeit;
- Verwirklichungen:
	- Öffentlichkeitsarbeit und Fortbildung der Allgemeinheit im Bereich der Forschungssoftware. (Issue #6, Stephan J.)
	- die Beratung von Gesetzgebungs- und Verwaltungsorganen sowie anderer öffentlicher bzw. dem Gemeinwohl verpflichteter Institutionen gemäß den vorgenannten Aufgaben und Zielen (Issue #6, Stephan J.)

### `null` 9
- Ziele:
	- `null`
- Verwirklichungen:
	- Förderung von Forschungsvorhaben zum Thema Software in der Wissenschaft (Issue #6, Stephan J.)

### `null` 10
- Ziele:
	- Die Förderung der Nutzung nationaler und internationaler Infrastrukturen im Bereich der wissenschaftlichen Software-Erstellung und Wartung durch fachliche und finanzielle Unterstützung der interessierten WissenschaftlerInnen. (Issue #6, Stephan J.)
- Verwirklichungen:
	- `null`

### bereits verallgemeinertere Verwirklichungen

- Durchführung wissenschaftlicher Veranstaltungen zum Themenkomplex Software in der Wissenschaft (Issue #6, Stephan D.)
- Erstellung und Publikation (auch elektronisch) von Informations- und Schulungsmaterial zum Themenkomplex Software in der Wissenschaft (Issue #6, Stephan D.)
- Förderung von Forschungsvorhaben, Programmen und Aktivitäten zum Thema Software in der Wissenschaft (Issue #6, Stephan D.)

**Comment by sdruskat** [comment]
Nach Zusammenführung schlage ich die Formulierung in #10 für die Satzung vor. Ich denke, dass dies eine gute Stelle ist, um einerseits ein möglichst allgemeines Ziel aufzustellen (wir hatten beim Call über ein generisches, also leicht anzupassendes Ziel gesprochen) und gleichzeitig ins Detail zu gehen.

Vorschläge zu Verwirklichungen folgen später.

**Comment by sdruskat** [comment]
Verwirklichungsformulierungsvorschlag jetzt auch in #10.

Dazu gibt es auch ein angefangenes Mapping von Verwirklichungspunkten zu Unterzwecken, Zielen und Verwirklichungen, falls das jmd. interessiert. Mir schien schon beim 2. Unterpunkt alles abgedeckt.

**Comment by StephanJanosch** [comment]
> - die Sicherstellung von Nachhaltigkeit und Verifizierbarkeit der wissenschaftlichen Softwareentwicklung als Teil von Forschungsprozessen;

Das ist ein starker Satz. Wollen wir das nicht eher _fördern_ statt _sicherstellen_.

**Comment by nuest** [comment]
> - die Professionalisierung von Softwareentwicklung in der Wissenschaft und Forschung durch Etablierung von Best Practices;

"durch Etablierung von Best Practices" ist der einzige Punkt wo wir neben dem Ziel auch noch den Weg andeuten. Ich schlage vor das zu streichen.

**Comment by StephanJanosch** [comment]
Vielleicht ist  https://github.com/DE-RSE/satzung/blob/master/vorschlaege_vereinsziele.md ein Stück zu lang?  Imho sollte die Liste nicht mehr als 7±2 Elemente haben.

Vielleicht können wir 

> - die Öffnung von wissenschaftlicher Software als zentraler Baustein einer offenen Wissenschaft im Sinne der "Open Science"-Bewegung;

auch in die Verwirklichung verschieben?

**Comment by BFrit** [comment]
ist 
"die Verankerung von Softwareveröffentlichungen im wissenschaftlichen Wertesystem..." nicht ein Weg, um "die Durchsetzung der Anerkennung von Softwareentwicklung als wissenschaftlicher Leistung " zu erreichen?
Daher die SW-Veröffentlichung lieber in die Verwirklichung schieben.

**Comment by StephanJanosch** [comment]
> Mehrfach- und Parallelentwicklung
> 
> Ziele:
> null
> Verwirklichungen:
> null

Ziele: Sichtbarkeit erhöhen
Verwirklichung: 
* Verzeichnisse benennen/verlinken/fördern/etablieren und deren Nutzung promoten

**Comment by nuest** [comment]
Verein ist gegründet.
