### ISSUE TITLE
Geschaeftsordnung elektronische Kommunikation PKI

### ISSUE THREAD

**Issue by astruck** [DE-RSE/satzung#8]
> Das Mitglied hat bei Kompromittierung des Schlüssels für Benachrichtigung des Vorstands zu sorgen.
Das Mitglied tauscht bei Kompromittierung oder Ablauf der Gueltigkeit des Schluessels diesen aus.

**Comment by knarrff** [comment]
Ich wuerde es so lassen. Wichtig ist, dass der Vorstand ueber eine Kompromittierung erfaehrt und somit mit dem Schluessel unterzeichnete Dokumente in der Zukunft als ungueltig erkennt. Ob das einzelne Mitglied nach einer Kompromittierung oder dem Ablauf der Gueltigkeit den Schluessel erneutert, sollte dem Mitglied ueberlassen bleiben.

**Comment by nuest** [comment]
Keine Aktivität für eine Weile, der § wurde nicht weiter diskutiert. Ich stimme auch zu, dass eine Erneuerung des Schlüssels dem Mitglied überlassen sein kann. Wir wollen ja als Verein nicht verlangen nur per Email kontaktiert zu werden, sondern bieten das als Möglichkeit an. Daher sehe ich das Mitglied in der Pflicht hier tätig zu werden wenn es will.
