### ISSUE TITLE
Geschaeftsordnung Schriftform

### ISSUE THREAD

**Issue by astruck** [DE-RSE/satzung#9]
Laut BGB § 32+33+37 erfordern bestimmte Dokumente die "(gesetzliche) Schriftform". Hier gefunden:
https://www.rkpn.de/vereinsrecht/veroeffentlichungen/die-schriftform-in-der-satzung.html
Hier ist mir noch nicht klar, ob wir das in der Geschaeftsordnung so festlegen koennen:

> Elektronische Dokumente im Sinne des letzten Absatzes genügen für alle als "schriftlich" bezeichneten Vorgänge in der Satzung.

**Comment by knarrff** [comment]
Im zitiertem Dokument wird gesagt: "Jedoch verlangt die elektronische Form in diesem Sinn, dass der Aussteller der Erklärung das elektronische Dokument mit einer qualifizierten elektronischen Signatur nach dem Signaturgesetz versehen muss (§ 126a Abs. 1 BGB). Über eine solche qualifizierte Signatur nach dem Signaturgesetz verfügen -wenn überhaupt- nur die wenigsten Vereine."

Im Satzungsentwurf steht momentan: "Schriftliche Erklärungen im Sinne dieser Satzung können auch elektronische Dokumente sein. Die Geschäftsordnung bestimmt Anforderungen und Zustellwege derartiger Dokumente."

und in der Geschaeftsordnung: "Elektronische Dokumente im Sinne von (TODO: Nummer des letzten Paragraphen der Satzung) der Satzung sind mit PGP/GPG oder mit S/MIME signierte E-Mails.

Damit kommt der derzeitige Stand der buchstabengestreuen Gesetzeslage recht nahe. Wenn man es genau nehmen wuerde, erfuellt er sie jedoch nicht vollkommen: gefordert wird eine "qualifizierte Signatur", und selbst-erstellte Schluessel ala PGP oder S/MIME zaehlen laut deutschem Gesetz nicht dazu. Fuer "qualifizierte Signaturen" muss man zum Ausstellen eines Schluessels ueber "Zertifizierungsstellen" gehen.

Da web-of-trust basierte Verfahren in der Praxis jedoch weitaus mehr verbreitet sind als andere (meine persoenliche Einschaetzung) und fuer unsere Zwecke auch ausreichen (auch da laut Ordnung der Schluessel direkt beim Verein hinterlegt wird), schlage ich vor, beim derzeitigen Text zu bleiben (S/MIME schliesst sowohl selbt generierte als auch Zertifizierungstellensignaturen ein).

**Comment by knarrff** [comment]
Ein weiteres Indiz dafuer, dass PGP und aehnliche ok sind: 

http://www.juramagazin.de/43484.html
"Weder PGP noch GnuPP erfüllen die Anforderungen des Signaturgesetzes an eine qualifizierte elektronische Signatur. Für viele Einsatzbereiche ist dies jedoch ohne Bedeutung." ...

Nachdem ich mir sowohl den Gesetzestext selbst, als auch diverse Auslegungen ansah, bin ich der Meinung, dass man fuer einen Verein die Schriftform im Prinzip selbst definieren kann (gewillkürten Schiftform), und die im Gesetzestext vorkommenden "gesetzlichen Schiftformen" effektiv nur einen "default" darstellen und durch einen expliziten Hinweis in einer Satzung geaendert werden koennen. Ich bin aber natuerlich auch kein Jurist und noch nichteinmal mit dem Thema naeher vertraut.

Vielleicht noch ein "Informationsschnipsel" (wenn auch kein sehr aussagekraeftiges): dieser Textteil wurde aus der Satzung eines bestehenden gemeinnuetzungen Vereins uebernommen.

**Comment by nuest** [comment]
@knarrff Ich denke das hier ist mit deinen Kommentaren und der aktuellen Formulierung im Satzungsentwurf erledigt. Die aktuelle Formulierung in der Geschäftsordnung ist

> 5. Elektronische Schriftform
> Elektronische Dokumente im Sinne von §11  der Satzung sind mit PGP/GPG oder mit S/MIME signierte E-Mails und deren Anhänge. Jedes Mitglied kann beim Vorstand einen öffentlichen Schlüssel bzw. sein Zertifikat hinterlegen, dessen Signatur die jeweiligen E-Mails tragen müssen. Das Mitglied hat bei Kompromittierung des Schlüssels für Benachrichtigung des Vorstands zu sorgen.
Elektronische Dokumente im Sinne des letzten Absatzes genügen für alle als "schriftlich" bezeichneten Vorgänge in der Satzung.
